### ISSUE TITLE
vsc 1.9.1+ using full document path as webstrate id on windows

### ISSUE THREAD

**Issue by thiemok** [Webstrates/vsce#5]
When creating new files the full file path is used as the webstrate id.
This happens on  Visual Studio Code v1.9.1 and v1.10.0 Insider on Windows, v1.9.1 on OSX works fine.

**Comment by raedle** [comment]
Thanks for reporting @thiemok . I'll check it.

**Comment by raedle** [comment]
@thiemok It's fixed in version 0.8.1

Previously, we have used `path.posix.basename` to extract the webstrate id from a filename. It's replaced by `path.basename` (see https://nodejs.org/api/path.html#path_path_basename_path_ext).

>path.basename('/foo/bar/baz/asdf/quux.html')
>// Returns: 'quux.html'

**Comment by thiemok** [comment]
Thanks for the quick fix!
